// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSYgwu6vOA8eUk73tptPcIEVIsTMq42iw',
    appId: '1:1031218914692:web:64cacd8349d356f899a9d1',
    messagingSenderId: '1031218914692',
    projectId: 'thang-946f5',
    authDomain: 'thang-946f5.firebaseapp.com',
    storageBucket: 'thang-946f5.firebasestorage.app',
    measurementId: 'G-CBKQ4QQ222',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-u1ezXWMmkEaz2PiL6jIIa5yAXSVm5ts',
    appId: '1:1031218914692:android:d12a6fb6ff31bf5899a9d1',
    messagingSenderId: '1031218914692',
    projectId: 'thang-946f5',
    storageBucket: 'thang-946f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiyQqQKHd8-fEn-s2Gb7BLNAzKRj8jfEo',
    appId: '1:1031218914692:ios:8bc57089d7335f6099a9d1',
    messagingSenderId: '1031218914692',
    projectId: 'thang-946f5',
    storageBucket: 'thang-946f5.firebasestorage.app',
    iosBundleId: 'com.example.thang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiyQqQKHd8-fEn-s2Gb7BLNAzKRj8jfEo',
    appId: '1:1031218914692:ios:8bc57089d7335f6099a9d1',
    messagingSenderId: '1031218914692',
    projectId: 'thang-946f5',
    storageBucket: 'thang-946f5.firebasestorage.app',
    iosBundleId: 'com.example.thang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSYgwu6vOA8eUk73tptPcIEVIsTMq42iw',
    appId: '1:1031218914692:web:f9e1c409a565f37d99a9d1',
    messagingSenderId: '1031218914692',
    projectId: 'thang-946f5',
    authDomain: 'thang-946f5.firebaseapp.com',
    storageBucket: 'thang-946f5.firebasestorage.app',
    measurementId: 'G-XHN95EBSV9',
  );
}
